server:
  port: 8084

spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5000

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://notification-db:5432/notification_service}
    username: ${SPRING_DATASOURCE_USERNAME:notification_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:notification_db_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

